-- 코드를 작성해주세요
WITH PARENT_ITEMS AS (
    SELECT PARENT_ITEM_ID AS IS_PARENT FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II
LEFT JOIN PARENT_ITEMS PI ON II.ITEM_ID = PI.IS_PARENT
WHERE IS_PARENT IS NULL
ORDER BY ITEM_ID DESC