-- 코드를 작성해주세요
WITH CHILD_COUNT_TBL AS (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT
    ID,
    IF (CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN CHILD_COUNT_TBL C ON ED.ID = C.PARENT_ID
ORDER BY ID