-- 코드를 입력하세요
WITH SUV_SEDAN AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE
        C.CAR_TYPE IN ('SUV', '세단') AND
        P.DURATION_TYPE = '30일 이상'
),
NOVEMBER_RENTED AS (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
),
NOT_RENTED AS (
    SELECT * FROM SUV_SEDAN
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID FROM NOVEMBER_RENTED
    )
)
SELECT
    CAR_ID, CAR_TYPE,
    ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100), 0) AS FEE
FROM NOT_RENTED
WHERE
    DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100) >= 500000 AND
    DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC