-- 코드를 입력하세요
SELECT
    WRITER_ID, NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        SUBSTRING(TLNO, 1, 3), '-',
        SUBSTRING(TLNO, 4, 4), '-',
        SUBSTRING(TLNO, 8, 4)
    ) AS '전화번호'
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY WRITER_ID DESC