-- 코드를 입력하세요
WITH JOINED_2021 AS (
    SELECT USER_ID FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
PURCHASED_USERS_2021 AS (
    SELECT OS.* FROM ONLINE_SALE OS
    JOIN JOINED_2021 J ON OS.USER_ID = J.USER_ID
)
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(USER_ID)) / J.C, 1) AS PURCHASED_RATIO
FROM PURCHASED_USERS_2021
JOIN (SELECT COUNT(*) AS C FROM JOINED_2021) AS J
GROUP BY MONTH(SALES_DATE)
ORDER BY YEAR, MONTH