-- 코드를 입력하세요
WITH TRUCK_TBL AS (
    SELECT CAR_ID, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
TRUCK_RENTAL_PERIOD AS (
    SELECT
        HISTORY_ID, RH.CAR_ID, DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_PERIOD,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 0
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    JOIN TRUCK_TBL T ON RH.CAR_ID = T.CAR_ID
),
TRUCK_DISCOUNT AS (
    SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT
    TRP.HISTORY_ID,
    IF (
        DISCOUNT_RATE IS NULL,
        RENTAL_PERIOD * DAILY_FEE,
        ROUND(RENTAL_PERIOD * DAILY_FEE * ((100 - DISCOUNT_RATE) / 100))
    ) AS FEE
FROM TRUCK_RENTAL_PERIOD TRP
LEFT JOIN TRUCK_DISCOUNT TD ON TRP.DURATION_TYPE = TD.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC