-- 코드를 입력하세요
WITH SUM_JULY AS (
    SELECT SHIPMENT_ID, SUM(TOTAL_ORDER) AS JULY_TOTAL FROM JULY
    GROUP BY FLAVOR
)
SELECT FLAVOR FROM FIRST_HALF FH
JOIN SUM_JULY SJ ON FH.SHIPMENT_ID = SJ.SHIPMENT_ID
ORDER BY TOTAL_ORDER + JULY_TOTAL DESC
LIMIT 3