-- 코드를 입력하세요
WITH RECURSIVE NUM AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM NUM
    WHERE HOUR < 23
),
OUT_COUNT AS (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR(DATETIME)
)
SELECT
    N.HOUR,
    IF (COUNT IS NULL, 0, COUNT)
FROM NUM N
LEFT JOIN OUT_COUNT O ON N.HOUR = O.HOUR