-- 코드를 작성해주세요
WITH FRONT_SKILL_CODE AS (
    SELECT CODE FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
CROSS JOIN FRONT_SKILL_CODE
WHERE SKILL_CODE & CODE
ORDER BY ID