-- 코드를 작성해주세요
WITH GRADE AS (
    SELECT
        HE.EMP_NO,
        AVG(SCORE) AS AVG_SCORE
    FROM HR_EMPLOYEES HE
    JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
    GROUP BY HE.EMP_NO
)
SELECT
    HE.EMP_NO, HE.EMP_NAME,
    CASE
        WHEN G.AVG_SCORE >= 96 THEN 'S'
        WHEN G.AVG_SCORE >= 90 THEN 'A'
        WHEN G.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN G.AVG_SCORE >= 96 THEN SAL * 0.2
        WHEN G.AVG_SCORE >= 90 THEN SAL * 0.15
        WHEN G.AVG_SCORE >= 80 THEN SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES HE
JOIN GRADE G ON HE.EMP_NO = G.EMP_NO
ORDER BY HE.EMP_NO