-- 코드를 입력하세요
WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEW AS (
    SELECT MAX(COUNT) AS MAX_REVIEW
    FROM REVIEW_COUNT
),
REVIEWEST AS (
    SELECT RC.MEMBER_ID FROM REVIEW_COUNT RC
    JOIN MAX_REVIEW MR ON RC.COUNT = MR.MAX_REVIEW
)
SELECT
    MEMBER_NAME, REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REVIEWEST R
JOIN REST_REVIEW RR ON R.MEMBER_ID = RR.MEMBER_ID
JOIN MEMBER_PROFILE MR ON R.MEMBER_ID = MR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT