-- 코드를 작성해주세요
WITH RARE_ITMES AS (
    SELECT ITEM_ID AS RARE_ITEM_ID FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM RARE_ITMES RI
JOIN ITEM_TREE IT ON RI.RARE_ITEM_ID = IT.PARENT_ITEM_ID
JOIN ITEM_INFO II ON IT.ITEM_ID = II.ITEM_ID
ORDER BY II.ITEM_ID DESC