-- 코드를 입력하세요
WITH FILTERED AS (
    SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
),
FREQUENT_CARS AS (
    SELECT CAR_ID FROM FILTERED
    GROUP BY CAR_ID
    HAVING COUNT(*) >=5
)
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM FILTERED
WHERE CAR_ID IN (SELECT CAR_ID FROM FREQUENT_CARS)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC