-- 코드를 작성해주세요
WITH BIGGEST_ECOLI_BY_YEAR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
    BE.YEAR,
    BE.MAX_COLONY - SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN BIGGEST_ECOLI_BY_YEAR BE ON YEAR(E.DIFFERENTIATION_DATE) = BE.YEAR
ORDER BY BE.YEAR, 2