-- 코드를 작성해주세요
WITH MAX_LENGTH_BY_TYPE AS(
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT
    ID,
    FN.FISH_NAME,
    MAX_LENGTH AS LENGTH
FROM FISH_INFO FI
JOIN MAX_LENGTH_BY_TYPE ML ON 
    FI.FISH_TYPE = ML.FISH_TYPE AND
    FI.LENGTH = MAX_LENGTH
JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
ORDER BY ID