-- 코드를 입력하세요
SELECT
    FOOD_PRODUCT.CATEGORY,
    FOOD_PRODUCT.PRICE AS 'MAX_PRICE',
    FOOD_PRODUCT.PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN
    (SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS SUB
    ON
        SUB.CATEGORY = FOOD_PRODUCT.CATEGORY AND
        SUB.PRICE = FOOD_PRODUCT.PRICE
ORDER BY MAX_PRICE DESC