-- 코드를 입력하세요
SELECT
    # 10000 * (PRICE DIV 10000) AS PRICE_GROUP,
    # FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP,
    TRUNCATE(PRICE, -4) AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP